### ISSUE TITLE
Update Badger tests

### ISSUE THREAD

**Issue by schomatis** [dgraph-io/tove#1]
I would like to use Tove to test Badger's latest version v1.5.0.

From what I'm seeing in the [`util`](https://github.com/dgraph-io/tove/blob/a9db6103db075e7be356560eeea38f9c0c8ee9d0/badger/util/util.go) package and the errors from running the [`run.sh`](https://github.com/dgraph-io/tove/blob/a9db6103db075e7be356560eeea38f9c0c8ee9d0/badger/run.sh) script this test should be updated to use Badger's transaction API and also the recently modified GC API.

```
# github.com/dgraph-io/tove/badger/util
util/util.go:12:21: undefined: badger.KV
util/util.go:25:5: opt.ValueGCRunInterval undefined (type *badger.Options has no field or method ValueGCRunInterval)
util/util.go:26:5: opt.ValueGCThreshold undefined (type *badger.Options has no field or method ValueGCThreshold)
util/util.go:30:13: undefined: badger.NewKV
util/util.go:46:17: undefined: badger.KV
util/util.go:52:18: undefined: badger.KV
util/util.go:52:40: undefined: badger.KVItem
util/util.go:53:14: undefined: badger.KVItem
util/util.go:64:22: undefined: badger.KV
```

@manishrjain @peterstace Any other modifications I should consider?

**Comment by manishrjain** [comment]
I haven't personally worked on this. But, yeah that sounds about the right direction.
